#!/usr/bin/env python3
#PBS -N a_cont
#PBS -r n
#PBS -o $PBS_JOBID.out
#PBS -e $PBS_JOBID.err
#PBS -l nodes=1:ppn=10:legacy
#PBS -l walltime=2:00:00:00
#PBS -A open

import getopt, os, time, multiprocessing, random, math, traceback, io, sys

def analysis(traj_id):
    os.chdir('../%d/'%traj_id)
    os.system("python ../analysis_contact.py")

traj_id_list = [1,2,3,4,5,6,7,8,9,10]
num_proc = 10
os.chdir(os.environ['PBS_O_WORKDIR'])

pool = multiprocessing.Pool(num_proc)
for traj_id in traj_id_list:
    pool.apply_async(analysis, (traj_id,))

while True:
    time.sleep(10)
    if len(pool._cache) == 0:
        print('All Done.')
        break

pool.close()
pool.join()
