#!/usr/bin/env python3
#PBS -N a_3cla_f_a
#PBS -r n
#PBS -o $PBS_JOBID.out
#PBS -e $PBS_JOBID.err
#PBS -l nodes=1:ppn=20:legacy
#PBS -l walltime=2:00:00:00
#PBS -A open

import getopt, os, time, multiprocessing, random, math, traceback, io, sys

def analysis(cor_file, dom_def, sec_def, traj, out, mask):
	os.system("calc_native_contact_fraction_v2.pl -i "+cor_file+" -d "+dom_def+" -s '"+sec_def+"' -t "+traj+" -m 1 -o "+out+" -k '"+mask+"' -r 1")

#mask = '86, 87, 88, 97, 98, 99, 100, 128, 129, 134, 138, 139, 140, 141, 142, 143, 144, 152, 154, 155, 156, 157, 158, 159, 162, 164, 165, 166, 167, 168, 186'
mask = '24-33, 86, 87, 88, 97, 98, 99, 100, 128, 129, 134, 138, 139, 140, 141, 142, 143, 144, 146-158, 159, 162, 164, 165, 166, 167, 168, 186'
np = 20
os.chdir(os.environ['PBS_O_WORKDIR'])

psf_file = os.popen('ls setup/*.psf').readlines()[0].strip()
cor_file = os.popen('ls setup/*.cor').readlines()[0].strip()
sec_def = os.popen('ls setup/secondary_*').readlines()[0].strip()
dom_def = os.popen('ls setup/domain_def*').readlines()[0].strip()

#traj_list = os.popen('ls | grep "^[0-9]\\+$"').readlines()
#traj_list = [t.strip() for t in traj_list]
traj_list = [str(i) for i in range(1,101)]

os.system("mkdir -p analysis/active_pocket_qbb")

pool = multiprocessing.Pool(np)
for traj_dir in traj_list:
    for i in range(10):
        pool.apply_async(analysis, (cor_file, dom_def, sec_def, traj_dir+'/traj_'+traj_dir+'_'+str(i+1)+'.dcd', 'analysis/active_pocket_qbb', mask))

while True:
    time.sleep(10)
    if len(pool._cache) == 0:
        print('All Done.')
        break

pool.close()
pool.join()
